using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenTerminal
{
    /**
     * This is generated by Visual Studio's "Paste Special" > Paste as Json Classes.
     * It models the json response of the nasdaq mock python server.
     */
        public class Rootobject
        {
            public Data data { get; set; }
            public object message { get; set; }
            public Status status { get; set; }
        }

        public class Data
        {
            public Headers headers { get; set; }
            public int limit { get; set; }
            public int offset { get; set; }
            public Row1[] rows { get; set; }
            public string symbol { get; set; }
            public Toptable topTable { get; set; }
            public int totalRecords { get; set; }
        }

        public class Headers
        {
            public string nlsPrice { get; set; }
            public string nlsShareVolume { get; set; }
            public string nlsTime { get; set; }
        }

        public class Toptable
        {
            public Headers1 headers { get; set; }
            public Row[] rows { get; set; }
        }

        public class Headers1
        {
            public string fiftyTwoWeekHighLow { get; set; }
            public string nlsVolume { get; set; }
            public string previousClose { get; set; }
            public string todayHighLow { get; set; }
        }

        public class Row
        {
            public string fiftyTwoWeekHighLow { get; set; }
            public string nlsVolume { get; set; }
            public string previousClose { get; set; }
            public string todayHighLow { get; set; }
        }

        public class Row1
        {
            public string nlsPrice { get; set; }
            public string nlsShareVolume { get; set; }
            public string nlsTime { get; set; }
        }

        public class Status
        {
            public object bCodeMessage { get; set; }
            public object developerMessage { get; set; }
            public int rCode { get; set; }
        }
}
